### ISSUE TITLE
Drop MinSDK

### ISSUE THREAD

**Issue by innoflash** [muigukenneth/ElegantDialog#1]
Hey buddy, lovely library there. Is it possible for you to drop the MinSDK fro 22 to like 18?

**Comment by muigukenneth** [comment]
@innoflash Thank you for trying the library. I will try and do the necessary downgrade on the next version.

**Comment by innoflash** [comment]
For sure, will try and fork it to see if its possible. I hope one of the libraries you used do not require minSDK of 22

**Comment by muigukenneth** [comment]
@innoflash i have pushed V 1.1.5 with min 18+ you can test so we can finally close this issue.

**Comment by innoflash** [comment]
Thanks buddy, wil check it out soonest and give u feedback


Thanks for ur efforts king

**Comment by muigukenneth** [comment]
@innoflash Your welcome Bro. Am glad you find the library useful.
Cheers.
