### ISSUE TITLE
Error implementing it in my project.

### ISSUE THREAD

**Issue by BoumBam** [muigukenneth/ElegantDialog#35]
Is that library available for JAVA ?
I tried to implement it in my project but I get that error.

**ERROR: Failed to resolve: com.github.muigukenneth:ElegantDialog:1.1.5
Show in Project Structure dialog
Affected Modules: app
**

I have three  questions:

1-
How could I implement it in my Java Project and how could I attach it to my button view ?

2- Do that library have long press(press on a button during 2 seconds for exapmle) feature before showing the popover ?

3- Is it possible to remove the avatar up of the popover ?

**Comment by muigukenneth** [comment]
Hi @BoumBam  maybe you forgot to add  
```
 repositories {
	...
	 maven { url 'https://jitpack.io' }
      }
```
in your build file.

1). You can access the ElegantDialog class from Java like this

```
    ElegantDialog dialog= new  ElegantDialog(context).setBackgroundBottomColor(Color.GREEN);
        dialog.show();
```
2). You can add your own 2 second long press on button by showing and dismissing the popup using

 ```
  dialog.show();
  dialog.dismiss();
```

3). Yes you can change avatar and load your custom one using Glide/Picasso ...check documentation for this
